### ISSUE TITLE
suggest stylelint over csscomb

### ISSUE THREAD

**Issue by Shuunen** [Shuunen/repo-checker#176]
```json
"devDependencies": {
    "stylelint": "^13.8.0",
    "stylelint-config-standard": "^20.0.0",
    "stylelint-declaration-use-variable": "^1.7.2",
    "stylelint-order": "^4.1.0"
  }
```

```json
"scripts": {
    "lint": "run-p lint:*",
    "lint:js": "eslint --fix --ignore-path .gitignore --ext .ts,.html .",
    "lint:css": "npx stylelint --fix \"src/**/*.css\""
}
```

& `stylelint.config.js`

```js
module.exports = {
  extends: 'stylelint-config-standard',
  plugins: [
    'stylelint-order',
    'stylelint-declaration-use-variable',
  ],
  rules: {
    'color-named': 'always-where-possible',
    'color-no-hex': true,
    'number-leading-zero': 'never',
    'order/properties-alphabetical-order': true,
    'sh-waqar/declaration-use-variable': ['z-index', ['/color/', { ignoreValues: ['transparent', 'currentColor', 'inherit', '/custom/'] }]],
    'unit-allowed-list': ['%', 's', 'rem', 'fr'],
  },
}
```

= ❤️ 🚀 

stylelint-disable exemple to be able to define colors with hex : 

```css
 body {
      /* stylelint-disable color-no-hex */
      --blue: #2c5e9e;
      /* stylelint-enable color-no-hex */
    }
```
